[package]
name = "romancalc"
version = "0.1.0"
authors = ["David Hewitt <1939362+davidhewitt@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
futures = "0.1"
http = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
